name: website

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - main
    # Alternative: only build for tags.
    # tags:
    #   - '*'
  workflow_dispatch:
## security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    container: 
      image: node:20-bookworm
    steps:
      - name: Install dependencies
        run: |
          apt update
          apt install -y python3 python3-pip

      - name: Install Python dependencies
        run: |
          pip install pdoc . --break-system-packages

      - run: python3 -m pdoc -d markdown -o docs plankapy

      - uses: forgejo/upload-artifact@v4
        with:
          path: docs

